In [1]:
import pandas as pd
import requests
import time

In [2]:
from medication_etl_src.api.api_anvisa import ApiAnvisa

In [3]:
api = ApiAnvisa()

In [4]:
s = time.time()
medicines = api.get_medicines()
e = time.time()

page:  0  of  1
Sleeping  5.570850145313691 seconds

KeyboardInterrupt:

In [5]:
codigos = [m.codigo_anvisa for m in medicines]

In [6]:
s = time.time()
presentations = api.get_presentations(codigos)
e = time.time()

Getting presentation  1 of  45242
Sleeping  2.76041199232811 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/6
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/6  with status  200
Request took  0.7183887958526611  seconds
Getting presentation  2 of  45242
Sleeping  4.800235576400472 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/7
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/7  with status  200
Request took  0.6578407287597656  seconds
Getting presentation  3 of  45242
Sleeping  2.085945944898908 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/14
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/14  with status  200
Request took  0.7759239673614502  seconds
Getting presentation  4 of  45242
Sleeping  5.416313300064195 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/68333
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/68333  with status  200
Request took  0.6724820137023926  seconds
Getting presentation  5 of  45242
Sleeping  6.669652693201169 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/137487
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/137487  with status  200
Request took  0.7272047996520996  seconds
Getting presentation  6 of  45242
Sleeping  5.749253364374786 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/25
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/25  with status  200
Request took  0.7050704956054688  seconds
Getting presentation  7 of  45242
Sleeping  5.088302245238513 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/164964
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/164964  with status  200
Request took  0.6673038005828857  seconds
Getting presentation  8 of  45242
Sleeping  2.5994758905929114 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/37
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/37  with status  200
Request took  0.6759612560272217  seconds
Getting presentation  9 of  45242
Sleeping  1.980557833041328 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124691
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124691  with status  200
Request took  0.706920862197876  seconds
Getting presentation  10 of  45242
Sleeping  4.915664732345202 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/43
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/43  with status  200
Request took  0.6847646236419678  seconds
Getting presentation  11 of  45242
Sleeping  2.809341347030245 seconds
Sleeping  1.5593842532225572 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/43
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/43  with status  200
Request took  0.703571081161499  seconds
Getting presentation  12 of  45242
Sleeping  6.587518385881916 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/57
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/57  with status  200
Request took  0.7229175567626953  seconds
Getting presentation  13 of  45242
Sleeping  5.421279896464574 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/137489
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/137489  with status  200
Request took  0.7953886985778809  seconds
Getting presentation  14 of  45242
Sleeping  5.847404886118216 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/66
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/66  with status  200
Request took  0.7820444107055664  seconds
Getting presentation  15 of  45242
Sleeping  3.0438287379426994 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124703
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124703  with status  200
Request took  0.654080867767334  seconds
Getting presentation  16 of  45242
Sleeping  8.443149561485896 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/71
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/71  with status  200
Request took  0.8308095932006836  seconds
Getting presentation  17 of  45242
Sleeping  5.563387040367089 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/72
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/72  with status  200
Request took  0.6708261966705322  seconds
Getting presentation  18 of  45242
Sleeping  5.298941214096367 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/74
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/74  with status  200
Request took  0.7859020233154297  seconds
Getting presentation  19 of  45242
Sleeping  4.116621485083534 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/75
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/75  with status  200
Request took  0.6498966217041016  seconds
Getting presentation  20 of  45242
Sleeping  7.3506632280977104 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/69833
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/69833  with status  200
Request took  0.6635866165161133  seconds
Getting presentation  21 of  45242
Sleeping  5.094356378304692 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/80
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/80  with status  200
Request took  0.7343840599060059  seconds
Getting presentation  22 of  45242
Sleeping  5.293473786983068 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124712
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124712  with status  200
Request took  0.7883210182189941  seconds
Getting presentation  23 of  45242
Sleeping  3.4370363165841065 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124713
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124713  with status  200
Request took  0.7187235355377197  seconds
Getting presentation  24 of  45242
Sleeping  3.5946333722892714 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/101
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/101  with status  200
Request took  0.8937973976135254  seconds
Getting presentation  25 of  45242
Sleeping  8.145471882491933 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/106
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/106  with status  200
Request took  0.8086943626403809  seconds
Getting presentation  26 of  45242
Sleeping  4.558478284780548 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/273631
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/273631  with status  200
Request took  0.7262134552001953  seconds
Getting presentation  27 of  45242
Sleeping  7.322415504467893 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/109
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/109  with status  200
Request took  0.7934379577636719  seconds
Getting presentation  28 of  45242
Sleeping  9.291029457196476 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/110
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/110  with status  200
Request took  0.7300674915313721  seconds
Getting presentation  29 of  45242
Sleeping  5.710651925752836 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124718
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/124718  with status  200
Request took  0.8263869285583496  seconds
Getting presentation  30 of  45242
Sleeping  2.91844199861195 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/69840
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/69840  with status  200
Request took  0.6550962924957275  seconds
Getting presentation  31 of  45242
Sleeping  7.007997970252522 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/341
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/341  with status  200
Request took  0.3174295425415039  seconds
Getting presentation  32 of  45242
Sleeping  4.437846675542625 seconds
Sleeping  3.132516172265853 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/341
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/341  with status  200
Request took  0.3463716506958008  seconds
Getting presentation  33 of  45242
Sleeping  3.590789949602679 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/341
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/341  with status  200
Request took  0.2723710536956787  seconds
Getting presentation  34 of  45242
Sleeping  4.778768076804781 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/344
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/344  with status  200
Request took  0.2894575595855713  seconds
Getting presentation  35 of  45242
Sleeping  5.609506417013044 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.3133401870727539  seconds
Getting presentation  36 of  45242
Sleeping  3.222952710007801 seconds
Sleeping  2.7731974766061116 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.32418131828308105  seconds
Getting presentation  37 of  45242
Sleeping  5.658377670240505 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.3530848026275635  seconds
Getting presentation  38 of  45242
Sleeping  9.17637356816008 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.28960156440734863  seconds
Getting presentation  39 of  45242
Sleeping  9.437760786759565 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.27520322799682617  seconds
Getting presentation  40 of  45242
Sleeping  8.577926305786232 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/6701
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/6701  with status  200
Request took  0.2719879150390625  seconds
Getting presentation  41 of  45242
Sleeping  6.863689027781951 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/6701
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/6701  with status  200
Request took  0.7657482624053955  seconds
Getting presentation  42 of  45242
Sleeping  1.734947484615024 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345  with status  200
Request took  0.7803549766540527  seconds
Getting presentation  43 of  45242
Sleeping  4.5384684207526185 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345  with status  200
Request took  0.33310699462890625  seconds
Getting presentation  44 of  45242
Sleeping  1.879394510631724 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345  with status  200
Request took  0.2736978530883789  seconds
Getting presentation  45 of  45242
Sleeping  3.0327889075755134 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345  with status  200
Request took  0.27634263038635254  seconds
Getting presentation  46 of  45242
Sleeping  4.050767846269088 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345  with status  200
Request took  0.261505126953125  seconds
Getting presentation  47 of  45242
Sleeping  5.926350308323678 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/345  with status  200
Request took  0.29313182830810547  seconds
Getting presentation  48 of  45242
Sleeping  2.273988477456136 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/373
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/373  with status  200
Request took  0.28281617164611816  seconds
Getting presentation  49 of  45242
Sleeping  2.2984872653622617 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/373
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/373  with status  200
Request took  0.2688753604888916  seconds
Getting presentation  50 of  45242
Sleeping  3.298863037540359 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/373
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/373  with status  200
Request took  0.2977278232574463  seconds
Getting presentation  51 of  45242
Sleeping  8.876304700650094 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/341
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/341  with status  200
Request took  0.29410505294799805  seconds
Getting presentation  52 of  45242
Sleeping  6.034023164970704 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.28323984146118164  seconds
Getting presentation  53 of  45242
Sleeping  6.015629776341141 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.32169270515441895  seconds
Getting presentation  54 of  45242
Sleeping  9.209365218380778 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.28157782554626465  seconds
Getting presentation  55 of  45242
Sleeping  4.736350230855686 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.3033134937286377  seconds
Getting presentation  56 of  45242
Sleeping  1.8400654512944963 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.3037540912628174  seconds
Getting presentation  57 of  45242
Sleeping  2.4838310987716223 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.2910139560699463  seconds
Getting presentation  58 of  45242
Sleeping  1.959993306049352 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.2821168899536133  seconds
Getting presentation  59 of  45242
Sleeping  2.551770210932361 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.2864110469818115  seconds
Getting presentation  60 of  45242
Sleeping  6.404378611701904 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396
Finished request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/396  with status  200
Request took  0.26662135124206543  seconds
Getting presentation  61 of  45242
Sleeping  6.0168342402332975 seconds
Starting request to  https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/6701

In [7]:
from stealth_requests import StealthSession
import random
import time

with StealthSession() as session:

    session.get("https://consultas.anvisa.gov.br")

    time.sleep(random.random())
    
    headers = {"Authorization": "Guest"}
    response = session.get(
        #"https://consultas.anvisa.gov.br/api/empresa/funcionamento?column=&count=10&filter%5BtipoProduto%5D=1&order=asc&page=1",
        "https://consultas.anvisa.gov.br/api/consulta/medicamento/produtos/codigo/346905",
        headers=headers
    )

DNSError: Failed to perform, curl: (6) Could not resolve host: consultas.anvisa.gov.br. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

In [2]:
da = response.json()

In [4]:
data

[{'ordem': 1,
  'cnpj': '00000000000434',
  'razaoSocial': 'KADY INDUSTRIA DE SABONETES E AFINS LTDA',
  'nomeFantasia': None,
  'autorizacao': '1012773',
  'novaAutorizacao': None,
  'numeroProcesso': '250000897582',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1985-01-03T00:00:00.000-0300',
  'cadastro': False,
  'ativa': False},
 {'ordem': 2,
  'cnpj': '00000000070050',
  'razaoSocial': 'LABORATORIO LOPES MAIA IND COM LOMASA',
  'nomeFantasia': None,
  'autorizacao': '1001646',
  'novaAutorizacao': None,
  'numeroProcesso': '250000714278',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1980-02-20T00:00:00.000-0300',
  'cadastro': False,
  'ativa': False},
 {'ordem': 3,
  'cnpj': '00000000070130',
  'razaoSocial': 'N ARAUJO & CIA LTDA',
  'nomeFantasia': None,
  'autorizacao': '1002317',
  'novaAutorizacao': None,
  'numeroProcesso': '250000476077',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1978-03-20T00:00:00.000-0300',
  'cadastro': False,
  'ativa': True},
 {'ordem': 4,
  'cnpj': '00000000070211',
  'razaoSocial': 'QUIMICA E FARMACEUTICA EKIS LTDA',
  'nomeFantasia': None,
  'autorizacao': '1002533',
  'novaAutorizacao': None,
  'numeroProcesso': '250000737777',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1980-10-20T00:00:00.000-0300',
  'cadastro': False,
  'ativa': False},
 {'ordem': 5,
  'cnpj': '00000000070300',
  'razaoSocial': 'FARMSEPS LAB QUIM FTCO LTDA',
  'nomeFantasia': None,
  'autorizacao': '1002595',
  'novaAutorizacao': None,
  'numeroProcesso': '250000617277',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1981-03-25T00:00:00.000-0300',
  'cadastro': False,
  'ativa': False},
 {'ordem': 6,
  'cnpj': '00000000070483',
  'razaoSocial': 'INSTITUTO QUIMICO DE BIOLOGIA ALMAR',
  'nomeFantasia': None,
  'autorizacao': '1002928',
  'novaAutorizacao': None,
  'numeroProcesso': '250001999999',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1980-09-05T00:00:00.000-0300',
  'cadastro': False,
  'ativa': False},
 {'ordem': 7,
  'cnpj': '00000000070564',
  'razaoSocial': 'LABORATORIO INDUSTRIAL UNIV.FEDERAL SANTA MARIA',
  'nomeFantasia': None,
  'autorizacao': '1003331',
  'novaAutorizacao': None,
  'numeroProcesso': '250000715377',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1978-03-29T00:00:00.000-0300',
  'cadastro': False,
  'ativa': True},
 {'ordem': 8,
  'cnpj': '00000000070645',
  'razaoSocial': 'LABORATORIO INDIGENA LTDA',
  'nomeFantasia': None,
  'autorizacao': '1003403',
  'novaAutorizacao': None,
  'numeroProcesso': '250000777477',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1980-07-02T00:00:00.000-0300',
  'cadastro': False,
  'ativa': False},
 {'ordem': 9,
  'cnpj': '00000000070726',
  'razaoSocial': 'LABORATORIO CLINICO SILVA ARUJO SA',
  'nomeFantasia': None,
  'autorizacao': '1003650',
  'novaAutorizacao': None,
  'numeroProcesso': '250001088877',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1980-11-27T00:00:00.000-0300',
  'cadastro': False,
  'ativa': False},
 {'ordem': 10,
  'cnpj': '00000000070807',
  'razaoSocial': 'LABORATORIO FARMACEUTICO J FERREIRA LTDA',
  'nomeFantasia': None,
  'autorizacao': '1004028',
  'novaAutorizacao': None,
  'numeroProcesso': '250000493977',
  'tipoProduto': 'Medicamento',
  'enderecoInternet': None,
  'numeroSac': None,
  'dataAutorizacao': '1981-05-11T00:00:00.000-0300',
  'cadastro': False,
  'ativa': False}]

In [ ]:
pres = api.get_presentations(codigos_produto)

In [8]:
df = pd.DataFrame(presentations)

In [9]:
df

,codigoProduto,codigoNotificacao,tipoProduto,dataProduto,nomeComercial,classesTerapeuticas,atcs,numeroRegistro,dataVencimento,mesAnoVencimento,...,rotulos,anexoRotulos,existeBula,tipoAutorizacao,processoMatriz,isProcessoClone,sinonimos,indicacoes,codigoCategoriaRegulatoria,dataCancelamento
0,6,0,1.0,2000-04-25T00:00:00.000-0300,(VITAMINAS A ) + ASSSOCIACÕES,[VITAMINAS E SUPLEMENTOS MINERAIS],[],104540166,None,042005,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,8.0,None
1,7,0,1.0,2000-05-19T00:00:00.000-0300,AC SALICILICO + AC BENZOICO + IODO,[ANTIMICOTICOS PARA USO TOPICO],[],119350001,None,052005,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,8.0,None
2,14,0,1.0,2001-06-04T00:00:00.000-0300,ALENDRONATO SODICO,[SUPRESSORES DA REABSORCAO OSSEA],[],100470305,None,052006,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,8.0,None
3,68333,0,1.0,2002-03-19T00:00:00.000-0300,ARNICA MONTANA,[FITOTERAPICO SIMPLES],[],104730021,None,032007,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,4.0,None
4,137487,0,1.0,2002-07-01T00:00:00.000-0300,ARNICA MONTANA L.,[FITOTERAPICO SIMPLES],[],131750004,None,062007,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,4.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1491,828,0,1.0,2001-04-23T00:00:00.000-0300,AMPICILINA,[PENICILINA DE AMPLO ESPECTRO],[],105770004,None,092001,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,8.0,None
1492,69958,0,1.0,1996-09-23T00:00:00.000-0300,AMPICILINA,[ANTIBIOTICOS SISTEMICOS SIMPLES],[],112330019,None,092011,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,8.0,None
1493,137538,0,1.0,2002-07-24T00:00:00.000-0300,AMPICILINA,[ANTIBIOTICOS SISTEMICOS SIMPLES],[],104450120,None,072007,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,8.0,None
1494,169707,0,1.0,2002-12-20T00:00:00.000-0300,AMPICILINA,[PENICILINA DE AMPLO ESPECTRO],[],146950032,None,122007,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,8.0,None
1495,166604,0,1.0,2003-01-01T00:00:00.000-0300,AMPICILINA,[PENICILINA DE AMPLO ESPECTRO],[],104650352,None,012013,...,[],[],False,REGISTRADO,"{'nomeProduto': None, 'codProduto': None}",False,,,5.0,None

In [ ]:
result = []

with StealthSession() as session:

    for medicine in codigos_produto:

        api._times_retried = 0

        # First get the home page to make requests more stealthy
        session.get("https://consultas.anvisa.gov.br")
        time.sleep(random.random())

        presentations: list[dict] = api._make_request(
            endpoint=f"/consulta/medicamento/produtos/codigo/{medicine}",
            session=session
        )

        result.append(presentations)

        time.sleep(10)

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df = pd.concat([
    df.drop(columns=['produto', 'empresa', 'processo']),
    pd.json_normalize(df['produto']),
    pd.json_normalize(df['empresa']),
    pd.json_normalize(df['processo']),
], axis=1)

In [ ]:
codigos_produto = df['codigo'].sample(5).tolist()

In [ ]:
codigos_produto

In [ ]:
medicines_df = df.copy()

medicines_df = pd.concat([
    medicines_df.drop(columns=['produto', 'empresa', 'processo']),
    pd.json_normalize(medicines_df['produto']),
    pd.json_normalize(medicines_df['empresa']),
    pd.json_normalize(medicines_df['processo']),
], axis=1)
medicines_df = medicines_df[medicines_df["registro_ativo"]].drop(columns=["registro_ativo"])

data_perf = []
for column in medicines_df.columns:
    examples = medicines_df[medicines_df[column].notnull()][column]
    perf = {
        "column": column,
        "type": type(examples.iloc[-1:].item()) if len(examples) else None,
        "example": examples.iloc[-1:].item() if len(examples) else None,
        "filled_values": len(medicines_df[medicines_df[column].notnull()]),
        "null_values": len(medicines_df[medicines_df[column].isnull()]),
        "unique_values": len(medicines_df[medicines_df[column].notnull()][column].unique()),
        "duplicated_values": len(medicines_df[medicines_df[column].notnull() & medicines_df[column].duplicated()]),
    }
    data_perf.append(perf)
data_perf = pd.DataFrame(data_perf)
data_perf["type"] = data_perf["type"].apply(lambda x: "STRING" if x == str else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "INTEGER" if x == int else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "FLOAT" if x == float else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "BOOLEAN" if x == bool else x)

In [ ]:
pd.DataFrame(data_perf).to_csv("Data Perf Registros Ativos.csv", encoding="utf-8")

In [ ]:
data = api.get_medicines()

In [ ]:
pres = pd.DataFrame(result)

In [33]:
analyses_df = df.copy()

analyses_df = pd.concat([
    analyses_df.drop(columns=['empresa', 'processo', 'processoMatriz']),
    pd.json_normalize(analyses_df['empresa'], sep='.').add_prefix('empresa.'),
    pd.json_normalize(analyses_df['processo'], sep='.').add_prefix('processo.'),
    pd.json_normalize(analyses_df['processoMatriz'], sep='.').add_prefix('processoMatriz.'),
], axis=1)

data_perf = []
for column in analyses_df.columns:

    _column= column
    examples = analyses_df[analyses_df[column].notnull()][column]
    _type= type(examples.iloc[-1:].item()) if len(examples) else None

    analyses_df[column] = analyses_df[column].apply(lambda x: None if x==[] else x)
    examples = analyses_df[analyses_df[column].notnull()][column]
    
    _example = examples.iloc[-1:].item() if len(examples) else None
    _filled_values = len(analyses_df[analyses_df[column].notnull()])
    _null_values = len(analyses_df[analyses_df[column].isnull()])
    _unique_values = len(analyses_df[analyses_df[column].notnull()][column].unique()) if _type not in (list, dict) else "-"
    _duplicated_values = len(analyses_df[analyses_df[column].notnull() & analyses_df[column].duplicated()]) if _type not in (list, dict) else "-"

    perf = {
        "column": _column,
        "type": _type,
        "example": _example,
        "filled_values": _filled_values,
        "null_values": _null_values,
        "unique_values": _unique_values,
        "duplicated_values": _duplicated_values
    }
    data_perf.append(perf)
data_perf = pd.DataFrame(data_perf)
data_perf["type"] = data_perf["type"].apply(lambda x: "STRING" if x == str else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "INTEGER" if x == int else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "FLOAT" if x == float else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "BOOLEAN" if x == bool else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "LIST" if x == list else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "MAP" if x == dict else x)

In [72]:
pd.DataFrame(data_perf).to_csv("Preço Máximo ao Governo.csv", encoding="utf-8")

In [29]:
df[df["tipoPriorizacao"].notnull()]["tipoPriorizacao"].iloc[10]

''

In [ ]:
analyses_df

In [ ]:

analyses_df

In [17]:
apresentacoes = []
for item in presentations:
    apresentacoes = apresentacoes + item['apresentacoes']

In [18]:
apresentacoes = pd.DataFrame(apresentacoes)

In [ ]:
apresentacoes

In [73]:
analyses_df = preco_max_cons.copy()
#analyses_df = analyses_df[~(analyses_df["ativa"])]

'''analyses_df = pd.concat([
    analyses_df,
    pd.json_normalize(analyses_df['embalagemSecundaria'], sep='.').add_prefix('embalagemSecundaria.'),
], axis=1)'''

data_perf = []
for column in analyses_df.columns:

    _column= column
    examples = analyses_df[analyses_df[column].notnull()][column]
    _type= type(examples.iloc[-1:].item()) if len(examples) else None

    analyses_df[column] = analyses_df[column].apply(lambda x: None if x==[] else x)
    examples = analyses_df[analyses_df[column].notnull()][column]
    
    _example = examples.iloc[-1:].item() if len(examples) else None
    _filled_values = len(analyses_df[analyses_df[column].notnull()])
    _null_values = len(analyses_df[analyses_df[column].isnull()])
    _unique_values = len(analyses_df[analyses_df[column].notnull()][column].unique()) if _type not in (list, dict) else "-"
    _duplicated_values = len(analyses_df[analyses_df[column].notnull() & analyses_df[column].duplicated()]) if _type not in (list, dict) else "-"

    perf = {
        "column": _column,
        "type": _type,
        "example": _example,
        "filled_values": _filled_values,
        "null_values": _null_values,
        "unique_values": _unique_values,
        "duplicated_values": _duplicated_values
    }
    data_perf.append(perf)
data_perf = pd.DataFrame(data_perf)
data_perf["type"] = data_perf["type"].apply(lambda x: "STRING" if x == str else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "INTEGER" if x == int else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "FLOAT" if x == float else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "BOOLEAN" if x == bool else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "LIST" if x == list else x)
data_perf["type"] = data_perf["type"].apply(lambda x: "MAP" if x == dict else x)

In [74]:
data_perf

,column,type,example,filled_values,null_values,unique_values,duplicated_values
0,SUBSTÂNCIA,STRING,ÓXIDO DE ZINCO;ÁCIDO ASCÓRBICO,25652,0,2263,23389
1,CNPJ,STRING,02.456.955/0001-83,25652,0,256,25396
2,LABORATÓRIO,STRING,NATULAB LABORATORIO S.A,25652,0,256,25396
3,CÓDIGO GGREM,INTEGER,540420050013307,25652,0,25651,1
4,REGISTRO,INTEGER,1384100600048,25652,0,25652,0
...,...,...,...,...,...,...,...
59,ANÁLISE RECURSAL,STRING,(AR),205,25447,18,187
60,LISTA DE CONCESSÃO DE CRÉDITO TRIBUTÁRIO (PIS/...,STRING,Negativa,25652,0,3,25649
61,COMERCIALIZAÇÃO 2023,STRING,Não,25652,0,2,25650
62,TARJA,STRING,- (*),25652,0,5,25647
63,DESTINAÇÃO COMERCIAL,None,None,0,25652,0,0

In [116]:
df.cadastro.any()

np.False_

In [44]:
embalagens = []
for apre in apresentacoes.to_dict(orient="records"):
    embalagens += apre['embalagemPrimariaTodas']
embalagens = pd.DataFrame(embalagens)

In [45]:
embalagens

                                           tipo observacao
0                      FRASCO DE PLASTICO OPACO       None
1                         FRASCO DE VIDRO AMBAR       None
2            BLISTER DE ALUMINIO/PLASTICO AMBAR       None
3            BLISTER DE ALUMINIO/PLASTICO AMBAR       None
4            BLISTER DE ALUMINIO/PLASTICO AMBAR       None
...                                         ...        ...
6548  BLISTER DE ALUMINIO/PLASTICO TRANSPARENTE       None
6549                      FRASCO DE VIDRO AMBAR       None
6550                      FRASCO DE VIDRO AMBAR       None
6551                      FRASCO DE VIDRO AMBAR       None
6552                      FRASCO DE VIDRO AMBAR       None

[6553 rows x 2 columns]

In [75]:
preco_max_cons = pd.read_excel(r"C:\Users\Marcelo\Desktop\Medicamentos\extracao-dados-medicamentos\data_pipelines\dags\jupyters\xls_conformidade_site_20250216_081743796.xls", skiprows=41)

In [65]:
preco_max_gov = pd.read_excel(r"C:\Users\Marcelo\Desktop\Medicamentos\extracao-dados-medicamentos\data_pipelines\dags\jupyters\xls_conformidade_gov_20250216_081743796.xls", skiprows=52)

In [67]:
preco_max_gov = preco_max_gov.dropna(how="all")

In [76]:
preco_max_cons

,SUBSTÂNCIA,CNPJ,LABORATÓRIO,CÓDIGO GGREM,REGISTRO,EAN 1,EAN 2,EAN 3,PRODUTO,APRESENTAÇÃO,...,PMC 22% ALC,RESTRIÇÃO HOSPITALAR,CAP,CONFAZ 87,ICMS 0%,ANÁLISE RECURSAL,LISTA DE CONCESSÃO DE CRÉDITO TRIBUTÁRIO (PIS/COFINS),COMERCIALIZAÇÃO 2023,TARJA,DESTINAÇÃO COMERCIAL
0,21-ACETATO DE DEXAMETASONA;CLOTRIMAZOL,18.459.628/0001-15,BAYER S.A.,538912020009303,1705600230032,7891106000956,-,-,BAYCUTEN N,"10 MG/G + 0,443 MG/G CREM DERM CT BG AL X 40 G",...,45.70,Não,Não,Não,Não,NaN,Negativa,Sim,- (*),NaN
1,ABATACEPTE,56.998.982/0001-07,BRISTOL-MYERS SQUIBB FARMACÊUTICA LTDA,505107701157215,1018003900019,7896016806469,-,-,ORENCIA,250 MG PO LIOF SOL INJ CT 1 FA + SER DESCARTÁVEL,...,NaN,Sim,Sim,Não,Não,NaN,Positiva,Sim,Tarja Vermelha,NaN
2,ABATACEPTE,56.998.982/0001-07,BRISTOL-MYERS SQUIBB FARMACÊUTICA LTDA,505113100020505,1018003900078,7896016808197,-,-,ORENCIA,125 MG/ML SOL INJ SC CT 4 SER PREENC VD TRANS ...,...,11381.34,Não,Sim,Sim,Não,NaN,Positiva,Sim,- (*),NaN
3,ABEMACICLIBE,43.940.618/0001-44,ELI LILLY DO BRASIL LTDA,507619060021902,1126001990018,7896382708442,-,-,VERZENIOS,50 MG COM REV CT BL AL AL X 30,...,4812.49,Não,Não,Não,Não,NaN,Negativa,Sim,Tarja Vermelha,NaN
4,ABEMACICLIBE,43.940.618/0001-44,ELI LILLY DO BRASIL LTDA,507619060022102,1126001990034,7896382708466,-,-,VERZENIOS,100 MG COM REV CT BL AL AL X 30,...,9624.92,Não,Não,Não,Não,NaN,Negativa,Sim,Tarja Vermelha,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25647,ÓXIDO CÚPRICO;ACETATO DE RACEALFATOCOFEROL;BET...,60.726.692/0001-81,MARJAN INDÚSTRIA E COMÉRCIO LTDA,524825010013107,1015500910166,7896226100272,-,-,VITERGAN ZINCO,COM REV CT BL AL PLAS PVC/PE/PVDC TRANS X 4,...,12.98,Não,Não,Não,Não,NaN,Negativa,Não,Tarja Sem Tarja,NaN
25648,ÓXIDO CÚPRICO;ACETATO DE RACEALFATOCOFEROL;BET...,60.726.692/0001-81,MARJAN INDÚSTRIA E COMÉRCIO LTDA,524825010013207,1015500910174,7896226100265,-,-,VITERGAN ZINCO,COM REV CT BL AL PLAS PVC/PE/PVDC TRANS X 4,...,14.92,Não,Não,Não,Não,NaN,Negativa,Não,Tarja Sem Tarja,NaN
25649,ÓXIDO CÚPRICO;SELENATO DE SÓDIO;ACETATO DE RAC...,60.659.463/0029-92,ACHE LABORATORIOS FARMACEUTICOS SA,500500101118422,1057302060014,7896658000010,-,-,ACCUVIT,COM REV CT FR PLAS OPC X 30,...,140.79,Não,Não,Não,Não,NaN,Negativa,Não,Tarja Sem Tarja,NaN
25650,ÓXIDO DE MAGNÉSIO;SIMETICONA;HIDRÓXIDO DE ALUM...,61.190.096/0001-92,EUROFARMA LABORATORIOS S.A.,508011804138416,1004306960107,7891317469610,7891317020118,-,SIMECO PLUS,120 MG/ML + 60 MG/ML + 7 MG/ML SUS OR CT FR VD...,...,14.42,Não,Não,Não,Não,NaN,Negativa,Não,Tarja Sem Tarja,NaN
25651,ÓXIDO DE ZINCO;ÁCIDO ASCÓRBICO,02.456.955/0001-83,NATULAB LABORATORIO S.A,540420050013307,1384100600048,7899470800325,-,-,VITER C + ZN,1 G + 10 MG COM EFERV CT TB PLAS X 10,...,35.28,Não,Não,Não,Não,NaN,Negativa,Não,- (*),NaN